=== attilinand/Camel-Routes/LTF_Transformer/data/Config/MessageHeaderEnrichRule.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MessageHeaderEnrichRules">
		<xs:complexType>
			<xs:sequence>
			    <xs:element ref="MessageHeaderEnrichRule" maxOccurs="unbounded"/> 
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	 <xs:element name="MessageHeaderEnrichRule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MessageHeaderEnrichRuleIdentifier"/>
				<xs:element ref="MessageHeaderEnrichValues"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageHeaderEnrichRuleIdentifier">
	<xs:complexType>
			<xs:sequence>
				<xs:element ref="MessageHeaderEnrichRuleIdentifierKeyValue" maxOccurs="unbounded"/>
				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	
	
	
	
	
	
	<xs:element name="MessageHeaderEnrichRuleIdentifierKeyValue" >
	
	<xs:complexType>
			<xs:sequence>
			    <xs:element ref="MessageHeaderEnrichRuleIdentifierKey"/>
			     <xs:element ref="MessageHeaderEnrichRuleIdentifierValue"/> 
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageHeaderEnrichRuleIdentifierKey" type="xs:string"/>
	<xs:element name="MessageHeaderEnrichRuleIdentifierValue" type="xs:string"/>
	<xs:element name="MessageHeaderEnrichValues">
	<xs:complexType>
			<xs:sequence>
			    <xs:element ref="MessageHeaderEnrichValueKeyValue" maxOccurs="unbounded"/>
			  
			</xs:sequence>
		</xs:complexType>
	
	</xs:element>
	
	
	
	<xs:element name="MessageHeaderEnrichValueKeyValue" >
	<xs:complexType>
			<xs:sequence>
			    <xs:element ref="MessageHeaderEnrichValueKey"/>
			     <xs:element ref="MessageHeaderEnrichValue"/> 
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MessageHeaderEnrichValueKey" type="xs:string"/>
	<xs:element name="MessageHeaderEnrichValue" type="xs:string"/>
	
	
	

</xs:schema>

=== attilinand/Camel-Routes/LTF_Transformer/directoryName/MessageHeaderEnrichValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<MessageHeaderEnrichRules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Config/MessageHeaderEnrichRule.xsd">
<!--   <MessageHeaderEnrichRule> -->
<!--     <MessageHeaderEnrichRuleIdentifier> -->
<!--       <MessageHeaderEnrichRuleIdentifierKeyValue> -->
<!--         <MessageHeaderEnrichRuleIdentifierKey>jms/jmsdestination</MessageHeaderEnrichRuleIdentifierKey> -->
<!--         <MessageHeaderEnrichRuleIdentifierValue>TrainEventQ</MessageHeaderEnrichRuleIdentifierValue> -->
<!--       </MessageHeaderEnrichRuleIdentifierKeyValue> -->
<!--       <MessageHeaderEnrichRuleIdentifierKeyValue> -->
<!--         <MessageHeaderEnrichRuleIdentifierKey>jms/jmstype</MessageHeaderEnrichRuleIdentifierKey> -->
<!--         <MessageHeaderEnrichRuleIdentifierValue>TrainEventSpecial</MessageHeaderEnrichRuleIdentifierValue> -->
<!--       </MessageHeaderEnrichRuleIdentifierKeyValue> -->
<!--     </MessageHeaderEnrichRuleIdentifier> -->
<!--     <MessageHeaderEnrichValues> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>MessageID</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>MessageType</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>SourceApplication</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>CorrelationID</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>TimeStamp</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--       <MessageHeaderEnrichValueKeyValue> -->
<!--         <MessageHeaderEnrichValueKey>Operation</MessageHeaderEnrichValueKey> -->
<!--         <MessageHeaderEnrichValue>MessageHeaderEnrichValue</MessageHeaderEnrichValue> -->
<!--       </MessageHeaderEnrichValueKeyValue> -->
<!--     </MessageHeaderEnrichValues> -->
<!--   </MessageHeaderEnrichRule> -->
  <MessageHeaderEnrichRule>
    <MessageHeaderEnrichRuleIdentifier>
      <MessageHeaderEnrichRuleIdentifierKeyValue>
        <MessageHeaderEnrichRuleIdentifierKey>abc</MessageHeaderEnrichRuleIdentifierKey>
        <MessageHeaderEnrichRuleIdentifierValue>123</MessageHeaderEnrichRuleIdentifierValue>
      </MessageHeaderEnrichRuleIdentifierKeyValue>
   </MessageHeaderEnrichRuleIdentifier>
    <MessageHeaderEnrichValues>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>MessageID</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>jms/jmsmessageid</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>MessageType</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>"TrainEvent"</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>SourceApplication</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>"MainFrame"</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>CorrelationID</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>jms/breadcrumbid</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>TimeStamp</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>SystemTime</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
      <MessageHeaderEnrichValueKeyValue>
        <MessageHeaderEnrichValueKey>Operation</MessageHeaderEnrichValueKey>
        <MessageHeaderEnrichValue>"NewTrainEvent"</MessageHeaderEnrichValue>
      </MessageHeaderEnrichValueKeyValue>
     </MessageHeaderEnrichValues>
  </MessageHeaderEnrichRule>
</MessageHeaderEnrichRules>
